# Generated by Django 6.0.3 on 2026-03-17 13:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RSSFeed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('url', models.URLField(unique=True)),
                ('category', models.CharField(choices=[('sports', 'Sports'), ('world_news', 'World News'), ('ai', 'AI'), ('tech', 'Tech'), ('politics', 'Politics'), ('health', 'Health'), ('other', 'Other')], default='other', max_length=32)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_fetched_at', models.DateTimeField(blank=True, null=True)),
                ('etag', models.CharField(blank=True, max_length=255)),
                ('last_modified', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'verbose_name': 'RSS feed',
                'verbose_name_plural': 'RSS feeds',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=64, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.CharField(help_text='GUID or stable ID from the RSS feed', max_length=512)),
                ('title', models.CharField(max_length=512)),
                ('slug', models.SlugField(blank=True, max_length=512)),
                ('summary', models.TextField(blank=True)),
                ('content', models.TextField(blank=True)),
                ('url', models.URLField(help_text='Canonical article URL')),
                ('image_url', models.URLField(blank=True)),
                ('author', models.CharField(blank=True, max_length=255)),
                ('language', models.CharField(blank=True, max_length=16)),
                ('published_at', models.DateTimeField()),
                ('fetched_at', models.DateTimeField(auto_now_add=True)),
                ('feed', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='articles', to='articles.rssfeed')),
                ('tags', models.ManyToManyField(blank=True, related_name='articles', to='articles.tag')),
            ],
            options={
                'ordering': ['-published_at'],
            },
        ),
        migrations.CreateModel(
            name='ArticleLike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='articles.article')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='article_likes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('user', 'article')},
            },
        ),
        migrations.AddIndex(
            model_name='article',
            index=models.Index(fields=['published_at'], name='articles_ar_publish_a51805_idx'),
        ),
        migrations.AddIndex(
            model_name='article',
            index=models.Index(fields=['feed', 'published_at'], name='articles_ar_feed_id_67b4fb_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='article',
            unique_together={('feed', 'external_id')},
        ),
    ]
